# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               William Lyon
tagline:             'Software, technology, startups, etc...'
description:         'Hi! I''m Will and this is where I write about software, technology, and startup stuff. You can find more from me <a href="https://twitter.com/lyonwj">@lyonwj</a> and on <a href="http://lyonwj.tumblr.com">tumblr.</a>'
url:                 http://lyonwj.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              William Lyon
  url:               https://twitter.com/lyonwj
  email:             lyonwj@gmail.com

# Custom vars
version:             1.0.0
