# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               lyonwj
tagline:             'William Lyon'
description:         'Software, technology, etc. By <a href="//twitter.com/lyon">@lyonwj</a>.'
url:                 http://lyonwj.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              William Lyon
  url:               https://twitter.com/lyonwj
  email:             lyonwj@gmail.com

# Custom vars
version:             1.0.0
